#!/usr/bin/env bash
# Sinh deploy/langfuse/.env với secrets ngẫu nhiên + bootstrap PDCA project.
# Idempotent: nếu .env đã tồn tại, sẽ ghi ra .env.new để bạn diff trước khi thay.
#
# Yêu cầu: openssl (đi kèm Git Bash trên Windows).

set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v openssl >/dev/null 2>&1; then
  echo "ERROR: openssl không có trong PATH. Cài Git Bash hoặc OpenSSL." >&2
  exit 1
fi

OUT=".env"
if [[ -f "$OUT" ]]; then
  OUT=".env.new"
  echo "INFO: .env đã tồn tại — ghi ra $OUT để bạn diff thủ công." >&2
fi

rand_hex()    { openssl rand -hex "${1:-32}"; }
# Loại bỏ ký tự cần URL-encode (=+/) để dùng thẳng trong DATABASE_URL không escape.
rand_base64() { openssl rand -base64 "${1:-32}" | tr -d '\n=+/' | head -c "${2:-40}"; }

ENCRYPTION_KEY=$(rand_hex 32)
NEXTAUTH_SECRET=$(rand_base64 32 40)
SALT=$(rand_base64 16 24)
POSTGRES_PASSWORD=$(rand_base64 24 32)
CLICKHOUSE_PASSWORD=$(rand_base64 24 32)
REDIS_AUTH=$(rand_base64 24 32)
MINIO_ROOT_PASSWORD=$(rand_base64 24 32)
# S3 access keys phải khớp MinIO root credentials — Langfuse dùng access_key_id=minio.
S3_EVENT_KEY=${MINIO_ROOT_PASSWORD}
S3_MEDIA_KEY=${MINIO_ROOT_PASSWORD}
LF_PUBLIC_KEY="pk-lf-$(rand_hex 16)"
LF_SECRET_KEY="sk-lf-$(rand_hex 24)"
ADMIN_PASSWORD=$(rand_base64 16 20)

cat > "$OUT" <<EOF
# Generated by scripts/generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# KHÔNG commit file này.

ENCRYPTION_KEY=${ENCRYPTION_KEY}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
SALT=${SALT}

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
REDIS_AUTH=${REDIS_AUTH}
MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=${S3_EVENT_KEY}
LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY=${S3_MEDIA_KEY}

NEXTAUTH_URL=http://localhost:3010
LANGFUSE_WEB_HOST_PORT=3010
CLICKHOUSE_NATIVE_HOST_PORT=9009
POSTGRES_HOST_PORT=5433
TELEMETRY_ENABLED=false

LANGFUSE_INIT_ORG_ID=pdca-org
LANGFUSE_INIT_ORG_NAME=PDCA Lab
LANGFUSE_INIT_PROJECT_ID=pdca-aws-security
LANGFUSE_INIT_PROJECT_NAME=PDCA AWS Security Agent
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=${LF_PUBLIC_KEY}
LANGFUSE_INIT_PROJECT_SECRET_KEY=${LF_SECRET_KEY}
LANGFUSE_INIT_USER_EMAIL=admin@pdca.local
LANGFUSE_INIT_USER_NAME=PDCA Admin
LANGFUSE_INIT_USER_PASSWORD=${ADMIN_PASSWORD}
EOF

chmod 600 "$OUT" 2>/dev/null || true

echo
echo "✅ Đã ghi $OUT"
echo
echo "Cặp credentials cho PDCA \`.env\`:"
echo "  LANGFUSE_PUBLIC_KEY=${LF_PUBLIC_KEY}"
echo "  LANGFUSE_SECRET_KEY=${LF_SECRET_KEY}"
echo "  LANGFUSE_HOST=http://localhost:3010"
echo
echo "Login UI: http://localhost:3010"
echo "  email:    admin@pdca.local"
echo "  password: ${ADMIN_PASSWORD}"
