REPORT_TEMPLATE = r"""
<div class="report-header">
  <h1 style="text-align: center; color: #2C3E50;">AWS SECURITY REMEDIATION REPORT</h1>
  <p style="text-align: center; color: #7F8C8D;">Generated by PDCA Security Agent | {{ sys.date }}</p>
</div>

---

# 1. Tóm tắt điều hành
{{ llm.executive_summary }}

---

# 2. Tổng quan hệ thống & Mục tiêu

## 2.1 Bối cảnh hệ thống
| Thuộc tính | Chi tiết |
| :--- | :--- |
| **Tài khoản AWS** | `{{ sys.account_id }}` |
| **Vùng (Region)** | {{ sys.region }} |
| **Phạm vi quét** | {{ sys.scan_scope }} |
| **Công cụ sử dụng** | Prowler, AWS SDK, PDCA Security Agent |

{{ system_overview_text }}

## 2.2 Mục tiêu đánh giá
{{ llm.assessment_goals }}

---

# 3. Tổng quan trước khắc phục

## 3.1 Trạng thái bảo mật ban đầu

**Thống kê:**
* **Tổng số phát hiện:** {{ summary.total_findings }}
* **ĐẠT (PASS):** {{ summary.total_pass }}
* **KHÔNG ĐẠT (FAIL):** {{ summary.total_fail }}

**Phân bổ mức độ nghiêm trọng:**
* Nghiêm trọng (Critical): **{{ summary.severity_breakdown.critical }}**
* Cao (High): **{{ summary.severity_breakdown.high }}**
* Trung bình (Medium): **{{ summary.severity_breakdown.medium }}**
* Thấp (Low): **{{ summary.severity_breakdown.low }}**

## 3.2 Phân tích trực quan

<table>
  <tr>
    <td align="center" width="50%">
      <img src="{{ chart_severity }}" style="max-width: 100%; height: auto;">
    </td>
    <td align="center" width="50%">
      <img src="{{ chart_pass_fail }}" style="max-width: 100%; height: auto;">
    </td>
  </tr>
</table>

## 3.3 Phân tích phát hiện
### Tổng quan các mục ĐẠT
{{ pass_overview }}

### Tổng quan các mục KHÔNG ĐẠT
{{ fail_overview }}

---

# 4. Bảng chi tiết các phát hiện

<div class="table-container">
<table class="styled-table">
<thead>
<tr style="background-color: #009879; color: #ffffff; text-align: left;">
  <th>STT</th>
  <th>Phát hiện</th>
  <th>Dịch vụ</th>
  <th>Tài nguyên</th>
  <th>Mức độ</th>
  <th>Trước</th>
  <th>Sau</th>
  <th>Trạng thái</th>
</tr>
</thead>
<tbody>
{% for row in table %}
<tr class="active-row">
  <td>{{ row.stt }}</td>
  <td>{{ row.finding }}</td>
  <td>{{ row.service }}</td>
  <td><small>{{ row.resource }}</small></td>
  <td>
    {% if row.severity|lower == 'critical' %} {% elif row.severity|lower == 'high' %} {% else %} {% endif %}
    {{ row.severity }}
  </td>
  <td>{{ row.before }}</td>
  <td>{{ row.after }}</td>
  <td style="font-weight: bold; color: {% if row.change == 'FIXED' %}green{% elif row.change == 'MANUAL' %}orange{% else %}red{% endif %};">
    {{ row.change }}
  </td>
</tr>
{% endfor %}
</tbody>
</table>
</div>

---

# 5. Chi tiết thực thi khắc phục

## 5.1 Khắc phục thành công
{% for f in success %}
### {{ loop.index }}. {{ f.action }}

**Thông tin thực thi:**
* **Tài nguyên:** `{{ f.resource }}`
* **Công cụ (Tool):** `{{ f.tool_name | default('N/A') }}`
* **Tham số (Payload):** `{{ f.execution_output | tojson }}`

> **PHÂN TÍCH KỸ THUẬT:**
>
> {{ f.llm_detail | trim | replace('\n', '\n> ') }}

<details>
<summary><i>Xem nhật ký thực thi chi tiết (Raw Log)</i></summary>

```yaml
{{ f.execution_log }}
```
</details>

---
{% endfor %}

## 5.2 Khắc phục thất bại
{% for f in failed %}
### {{ loop.index }}. {{ f.action }}
**Tài nguyên:** `{{ f.resource }}`

> **Phân tích lỗi:**
> {{ f.llm_detail }}

```yaml
{{ f.execution_log }}
```

---
{% endfor %}

---

# 6. Yêu cầu khắc phục thủ công

{% if manual | length == 0 %}
*Tuyệt vời! Không yêu cầu can thiệp thủ công.*
{% endif %}

{% for f in manual %}
> **Yêu cầu thủ công #{{ loop.index }}**
>
> **Vấn đề:** {{ f.description }}
>
> **Tài nguyên:** `{{ f.resource }}` | **Mức độ:** {{ f.severity }}
>
> **Tại sao cần thủ công?**
> {{ f.manual_reason }}
>
> {% if f.verification and f.verification.before %}
> **Trạng thái hiện tại:**
> ```yaml
> {{ f.verification.before | tojson(indent=2) }}
> ```
> {% endif %}
>
> **Kế hoạch hành động:**
> {% if f.remaining_actions %}
> {% for a in f.remaining_actions %}
> * [ ] {{ a }}
> {% endfor %}
> {% endif %}
>
> **HƯỚNG DẪN CHI TIẾT:**
> {{ f.llm_manual_guide | replace('\n', '\n> ') }}

<br>
{% endfor %}

---

# 7. Đánh giá sau khắc phục

## 7.1 Tóm tắt hiệu quả

| Chỉ số | Trước khắc phục | Sau khắc phục | Thay đổi |
| :--- | :---: | :---: | :---: |
| **ĐẠT (PASS)** | {{ post.initial_pass }} | **{{ post.final_pass }}** | {% set p_diff = post.final_pass - post.initial_pass %}{% if p_diff > 0 %} Tăng {{ p_diff }}{% elif p_diff < 0 %} Giảm {{ p_diff | abs }}{% else %} Giữ nguyên{% endif %} |
| **KHÔNG ĐẠT (FAIL)** | {{ post.initial_fail }} | **{{ post.final_fail }}** | {% set f_diff = post.final_fail - post.initial_fail %}{% if f_diff < 0 %} Giảm {{ f_diff | abs }}{% elif f_diff > 0 %} Tăng {{ f_diff }}{% else %} Giữ nguyên{% endif %} |

**Trạng thái khắc phục:**
* **Tự động sửa:** {{ post.fixed }}
* **Cần thủ công:** {{ post.manual }}
* **Lỗi trong quá trình sửa (Error):** {{ post.failed }}

## 7.2 Chi tiết thay đổi

### Các phát hiện đã sửa tự động
{% if success %}
{% for f in success %}
* {{ f.description }} (`{{ f.resource }}`)
{% endfor %}
{% else %}
_Không có phát hiện nào được sửa tự động._
{% endif %}

### Yêu cầu chú ý thủ công
{% if manual %}
{% for f in manual %}
* {{ f.description }} (`{{ f.resource }}`)
{% endfor %}
{% else %}
_Không có phát hiện thủ công._
{% endif %}

### Các lỗi tồn đọng
{% if failed %}
{% for f in failed %}
* {{ f.description }} (`{{ f.resource }}`)
{% endfor %}
{% else %}
_Không có lỗi trong lúc sửa._
{% endif %}

## 7.3 Đánh giá của chuyên gia
{{ post_remediation_analysis }}

---

# 8. Khuyến nghị chiến lược

{{ post_remediation_recommendations }}

<br>
<hr>
<p style="text-align: center; font-size: 0.8em; color: #999;">
    End of Report - Generated by LangChain & Ollama
</p>
"""
